permalink: pretty
theme: jekyll_patternbot
patternbot:
  title: "Green Java"
  description: |
    An online coffee roasting company that specializes in sustainably sourcing and producing the best quality of coffee.

patternbot:
  font_url: "https://fonts.googleapis.com/css?family=Merriweather:900|Roboto:400,700&display=swap"
  colors:
    background: "--color-primary"
    accent: "--color-accent"
  rationales:
    typefaces.primary: |
      Roboto was selected because it is a modern and clean sans-serif that is easy to read and reflects the tone of the company. Roboto is to be used for all body copy and most headings.
    typefaces.secondary: |
      Merriweather is to be used only for numerical headings that serve as decoration.
    colors.primary: |
      The primary color reflects the environmentally conscious approach that Green Java incorporates into their products. It should be used for most text elements and as a background color.
    colors.accent: |
      The accent colors are more neutral, earthy tones and should be used primarily for buttons and some textual elements.
