title: "Form"
description: |
  This is the form the user will fill out when purchasing items from the site.

patterns:
  text:
    title: "Text"
    description: |
      The user will be prompted to type in any information required for the order.

  select:
    title: "Select"
    description: |
      The user will be asked to select a piece of information pertinent to the order.

  email:
    title: "Email"
    description: |
      The user will be asked to enter their email address.

  phone:
    title: "Phone Number"
    description: |
      The user will be prompted to enter a phone number.

  submit:
    title: "Submit"
    description: |
      This button will submit the information in the form and lead the user to the shipping page.
